language: python
python:
- '3.6'
install:
- travis_wait pip install ansible>=2.5 molecule apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: SPX6cFGPw63zvL58qHP/PrO6NXBR1ZDkLUuH5OcLIS/MCfhSqgxVBw7ePb/quZmJ28pS+OUlrPIJCHDwifMHX3B6q5fUadyXVGBg6/rEZl4wAgT/Q5kFcN8dEf05P2TfqfC5K94DCRb5pZT7rGuA0PTHfdavTfTEBLXVDjW4VKm2hqc72wRjwO1r7itlGfWaAWcetjMj7y82anxBTlmk3Au2jsVNSPJ8eSpxpOotUjQAehEJuHnk/SwrTUlSWi+V3KfRG1Tsn3gynygRN1rINeL4IptZStcB31W1mmQTMZVF6auneokjBPjT6RX3SxvOYSUjwPnNdM5Q95l+kKwZlPFSI0Md3ubrKZNZQ4rSDplc5hXjQu4ApI8qPNp1xB4chbEHavn5Z70NiNTD5BoeAgqkfugfsnbp0KTWt8pHvPrMcFGmxl7eTgPC4N14Pue25qbN1GNTrpAUdVdDVY9kWBbh+mP1/m0wa9H+p/Rp6QB64yvExqHtKYYEj6EYxrlkKHUUB3IJf8qbQ0F0s4rz+RuD4YuxhScT0uajLrGseXYhQAyYmSROdL2UOjTZMf21ileD1YD1/Ywush/Z03YBHr8kOjCKYT3AUkBXtvL0Vz6G7wWK4ig2f+HuhgKCjeAxIGQ8DQSa2vEJkVxdw94ZrVs2AHFViKLWdy/USwbFXNE=
  - secure: MhWVdabGyTZgwP4gpW/72vO37KxLG3dzCmhsbOS1tbtpYp5YUA6+VGcFZThP9O6WY9ASW+2FXF2Ss/IpITXnUwCirt8A1RoDB2RIuOZ4IaLtvU3U60ZLInxKXKG9WK+qG77Z8X2hTnAj3TcG+AcfFknt7AaSCp3UHxYsmnFdN+N1VOlhF9mgXxLMfwpoGNR8nATWjpuNT7zvyTewLRMtaPq77Opo/7pYQPJi4Xo4x+vYnwBizli87O5ezEXxJ+p+rPykvOae3G1eqiMVBj47cccvZl0XIZs1rYu7vMnt8SVeqRprTK3ruY32Iual+0gJB/VaW31713eUIxFuNQMFimGyCKn9fbgLwCSfvY2xPwZll7qUpFUcfY4TaWq9H93Ny8iQm7SmzrhFdStyaognLTqJFZ93lqeXWdEAOzDgSKG1rOAnwWYtovdPhqMVYi7yQKAwDCise8IMkbRFtdAmd29hkdIiEdG2mcN3l0P28vnqUo+2sOaRRN3M8DLPqxor544rzKD/jJzlaQqHXZgVjkFD7hJ/sxUzGMEfIwgQL651gFASg0krNVNg9o/PeuBrDnLCiJgbdAzIepv+GRS9DgkwUvSsyrhDYw83+lOVfO7rV+TFzKFQyO+qcm6o0+8qhSjTGP6b2ni3I5NzJbg1rjLWADK4d64uLzCNNYChYYE=
  - secure: N5qCS25TcAfG9MBLCSAcuifVrQCcktGJH3FEoHr9Yfot9I10U2AFma0qvHZbY7K60H4pCN2qBhj+AK3mhthrtS5R9BSRl3fQgPT9gd534t03l/b47bi7Z2699gFeX6XJZUtZbNN1RAosx9DNOtGYuNtd56i5jby1sxfBKbCqF9IMDLQZXxOaZAytM+mi57oCuJcn61e0E/ozyT276LD3dKXU0C6oeaUpD0NRh+zHzabXHvGeKclsRW7N+6wPOzVNwGwqNRdJzCl3BeNrxSwvOAk4tlQ+pZJfpIlcGGHJPLKGb+V/tDno9cOcz+078aZ7ZXQziU9Nb1nPHf5aifctmU3DtsoxBTGPpCcs8X6gr9KaBbseNOWQ83IpGHiyFWuvOHhuc8jfVNhxXFgAnmNMb5Yoz6IaxD6XEah5B1J0x4vH9t4TKcU5iJfxnZH4jAHkSvgiMFQ+vXEV/7dUkUez2JGCO5xCvpeFWSCMf7aYPlZYG6DZul2RMreK180VWDhmB9bC43LvsUclnbyci4Q8aXdHDBGm/Yxc//YNVakeRBz02lHtz2+FJPLvJCtsTchg9FsCIAoA1SMRZxMCZBA9LBid2ZBg9m2OhYEhP4zIFELvkTjL01rZC1a1TEDljrx0EPgvcKAqjZZVNJbDTK7f1tvZNc5FhY5JLFS/BsrCf3w=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_04b72bf9862c_key -iv $encrypted_04b72bf9862c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- > /home/travis/.ssh/known_hosts
notifications:
  slack:
    secure: 3yF+dBkMvc4UWNOZK1PYTMbZ4qYt0hEev6GKaWrXRVFALoonwlCiEL43aeNucN+eKqTVcBTzTmPqZe83UZ0Y2lvUopx64Ni4O3a8LDLWa/I7kUPrdOnl+eAqoWjH72aTYStgMUl5NBLebRK70TOrJ+9+heiKxOJWEyEi1mAMyOVP761qJNCU0XiFDJqB/Lc3w31MWBJVNwrHAwyuieOjIF623UYSlIorDUG/XQcL+gsksHh8rCa7HlrRfaqfQMYxOOz6nbedL+IBmeVMOjyFklDXL9U2MSaKdG7bCj+oyTELXiYQpFGBOaXOOcxJTQFy41qPsPo5zwyMk3ryfQ2txNM5T3alcDuoNhPfBuOOSScDC8mIue0RxWwZgFh13Z5+mkm8RskfVNDB/7hWbMDb8cJMWeST/88PA47EE31TpEveJB2kJgkNjVNZJue4CChUuKK2yG3E7pGB8jOWUXhvl6PYE8/b2n+XvCLV1ZRqKCucgGXiLKmRELPvo0cJ2KOC1E4m7pzldiF02og/jCKqlFw4zb0EhWA2fU3FTaUNMueJbQKb3Z0SQHMG3WyFTaf1+/1SESpEjonvgZAdEtjhx55AFB1dA4VEskVoi61Rdflmn/KhkNZmG65wIDXhHh2yRWaOT9adwzOlbAiqrVp7BuzuhPnYbBdoBhMCAJXAzt4=
